### PR TITLE
Add Vector Finance

### PR DESCRIPTION
**Pull request by Revolutionary-Spaces**
IMG: https://drive.google.com/file/d/1nrPSEzIkje6uxT0-uN_kFFjp0enKU4Ic/view?usp=sharing

### CODE REVIEW

**Comment by k-822** [comment]
Please submit image in format detailed in readme and we'll get this uploaded.

**Comment by Revolutionary-Spaces** [comment]
@k-822 thanks: here is that image - https://drive.google.com/file/d/1rw2QLAze8_Q78E5nT2fG7oTulAU65BiO/view?usp=sharing

**Comment by k-822** [comment]
Hi, please upload image in img file as described in the readme and than this can be loaded.

**Comment by Revolutionary-Spaces** [comment]
VTX-80px

**Comment by Revolutionary-Spaces** [comment]
@k-822 I don't have the ability to upload files directly to the img folder but have left the image in a comment above and a pull request.

**Pull request merged**
